geonode/layers/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls.defaults import patterns, url

js_info_dict = {
    'packages': ('geonode.layers',),
}

urlpatterns = patterns(
    'geonode.layers.views',
    url(r'^$', 'layer_list', name='layer_browse'),
    url(r'^tag/(?P<slug>[-\w]+?)/$', 'layer_tag', name='layer_browse_tag'),
    url(r'^acls/?$', 'layer_acls', name='layer_acls'),
    url(r'^resolve_user/?$', 'resolve_user', name='layer_resolve_user'),
    url(r'^upload$', 'layer_upload', name='layer_upload'),
    url(r'^download$', 'layer_batch_download', name='layer_batch_download'),
    url(r'^(?P<layername>[^/]*)$', 'layer_detail', name="layer_detail"),
    url(r'^(?P<layername>[^/]*)/metadata$', 'layer_metadata',
        name="layer_metadata"),
    url(r'^(?P<layername>[^/]*)/remove$', 'layer_remove', name="layer_remove"),
    url(r'^(?P<layername>[^/]*)/replace$', 'layer_replace',
        name="layer_replace"),
    url(r'^(?P<layername>[^/]*)/style$', 'layer_style', name="layer_style"),
    url(r'^(?P<layername>[^/]*)/style/upload$','layer_style_upload',name='layer_style_upload'),
    url(r'^(?P<layername>[^/]*)/style/manage$','layer_style_manage',name='layer_style_manage'),
    url(r'^(?P<layername>[^/]*)/permissions$', 'layer_permissions',
        name='layer_permissions'),
    url(r'^(?P<layername>[^/]*)/edit-check?$', 'feature_edit_check',
        name="feature_edit_check")
    #url(r'^api/batch_permissions/?$', 'batch_permissions',
    #    name='batch_permssions'),
    #url(r'^api/batch_delete/?$', 'batch_delete', name='batch_delete'),
)

geonode/maps/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls.defaults import patterns, url

js_info_dict = {
    'packages': ('geonode.maps',),
}

urlpatterns = patterns('geonode.maps.views',
    url(r'^$', 'map_list', name='maps_browse'),
    url(r'^tag/(?P<slug>[-\w]+?)/$', 'maps_tag', name='maps_browse_tag'),
    url(r'^new$', 'new_map', name="new_map"),
    url(r'^new/data$', 'new_map_json', name='new_map_json'),
    url(r'^(?P<mapid>\d+)$', 'map_detail', name='map_detail'),
    url(r'^(?P<mapid>\d+)/view$', 'map_view', name='map_view'),
    url(r'^(?P<mapid>\d+)/data$', 'map_json', name='map_json'),
    url(r'^(?P<mapid>\d+)/download$', 'map_download', name='map_download'),
    url(r'^(?P<mapid>\d+)/wmc$', 'map_wmc', name='map_wmc'),
    url(r'^(?P<mapid>\d+)/wms$', 'map_wms', name='map_wms'),
    url(r'^(?P<mapid>\d+)/remove$', 'map_remove', name='map_remove'),
    url(r'^(?P<mapid>\d+)/metadata$', 'map_metadata', name='map_metadata'),
    url(r'^(?P<mapid>\d+)/embed$', 'map_embed', name='map_embed'),
    url(r'^(?P<mapid>\d+)/permissions$', 'map_permissions', name='map_permissions'),
    url(r'^(?P<mapid>\d+)/thumbnail$', 'map_thumbnail', name='map_thumbnail'),
    url(r'^check/$', 'map_download_check', name='map_download_check'),
    url(r'^embed/$', 'map_embed', name='map_embed'),
    url(r'^(?P<layername>[^/]*)/attributes', 'maplayer_attributes', name='maplayer_attributes'),
    #url(r'^change-poc/(?P<ids>\w+)$', 'change_poc', name='maps_change_poc'),
)

geonode/proxy/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls.defaults import patterns

urlpatterns = patterns('geonode.proxy.views',
    (r'^proxy/', 'proxy'),
    (r'^gs/rest/styles', 'geoserver_rest_proxy', dict(
        proxy_path='/gs/rest/styles', downstream_path='rest/styles')),
    (r'^gs/rest/layers', 'geoserver_rest_proxy', dict(
        proxy_path='/gs/rest/layers', downstream_path='rest/layers')),
)

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView

import geonode.proxy.urls

# Setup Django Admin
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

    # Static pages
    url(r'^$', 'geonode.views.index', name='home'),
    url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
    url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

    # Layer views
    (r'^layers/', include('geonode.layers.urls')),

    # Map views
    (r'^maps/', include('geonode.maps.urls')),

    # Catalogue views
    (r'^catalogue/', include('geonode.catalogue.urls')),

    # Search views
    (r'^search/', include('geonode.search.urls')),

    # Upload views
    (r'^upload/', include('geonode.upload.urls')),

    # GeoServer Helper Views 
    (r'^gs/', include('geonode.geoserver.urls')),

    # Social views
    (r"^account/", include("account.urls")),
    (r'^people/', include('geonode.people.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^comments/', include('dialogos.urls')),
    (r'^ratings/', include('agon_ratings.urls')),
    (r'^activity/', include('actstream.urls')),
    (r'^announcements/', include('announcements.urls')),
    #(r'^notifications/', include('notification.urls')),
    (r'^messages/', include('user_messages.urls')),
    (r'^social/', include('geonode.social.urls')),
    # Accounts
    url(r'^account/ajax_login$', 'geonode.views.ajax_login',
                                       name='account_ajax_login'),
    url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup',
                                       name='account_ajax_lookup'),

    # Meta
    url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'), name='lang'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
                                  js_info_dict, name='jscat'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                                  {'sitemaps': sitemaps}, name='sitemap'),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^admin/', include(admin.site.urls)),

    )

#Documents views
if settings.DOCUMENTS_APP:
    urlpatterns += patterns('',
        (r'^documents/', include('geonode.documents.urls')),
    )

urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

geonode/social/models.py
import geonode.social.signals

geonode/upload/models.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
from geonode.maps.models import Layer

from geonode.geoserver.uploader.uploader import NotFound
from geonode.upload.utils import gs_uploader
from geonode.utils import ogc_server_settings

from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

import cPickle as pickle
from datetime import datetime
import logging
from os import path
import shutil


class UploadManager(models.Manager):
    def __init__(self):
        models.Manager.__init__(self)
        
    def update_from_session(self, upload_session):
        self.get(import_id = upload_session.import_session.id).update_from_session(upload_session)
        
    def create_from_session(self, user, import_session):
        return self.create(
            user = user, 
            import_id = import_session.id, 
            state= import_session.state)
            
    def get_incomplete_uploads(self, user):
        return self.filter(user=user, complete=False).exclude(state=Upload.STATE_INVALID)
    
        
class Upload(models.Model):
    objects = UploadManager()
    
    import_id = models.BigIntegerField(null=True)
    user = models.ForeignKey(User, null=True)
    # hold importer state or internal state (STATE_)
    state = models.CharField(max_length=16)
    date = models.DateTimeField('date', default = datetime.now)
    layer = models.ForeignKey(Layer, null=True)
    upload_dir = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=64, null=True)
    complete = models.BooleanField(default = False)
    # hold our serialized session object
    session = models.TextField(null=True)
    # hold a dict of any intermediate Layer metadata - not used for now
    metadata = models.TextField(null=True)
    
    class Meta:
        ordering = ['-date']
    
    STATE_INVALID = 'INVALID'
    
    def get_session(self):
        if self.session:
            return pickle.loads(str(self.session))
        
    def update_from_session(self, upload_session):
        self.state = upload_session.import_session.state
        self.date = datetime.now()
        if "COMPLETE" == self.state:
            self.complete = True
            self.session = None
        else:
            self.session = pickle.dumps(upload_session)
        if self.upload_dir is None:
            self.upload_dir = path.dirname(upload_session.base_file)
            self.name = upload_session.layer_title or upload_session.name
        self.save()
        
    def get_resume_url(self):
        return reverse('data_upload') + "?id=%s" % self.import_id
    
    def get_delete_url(self):
        return reverse('data_upload_delete', args=[self.import_id])
        
    def get_import_url(self):
        return "%srest/imports/%s" % (ogc_server_settings.LOCATION, self.import_id)
    
    def delete(self, cascade=True):
        models.Model.delete(self)
        if cascade:
            try:
                session = gs_uploader().get_session(self.import_id)
            except NotFound:
                session = None
            if session:
                try:
                    session.delete()
                except:
                    logging.exception('error deleting upload session')
            if self.upload_dir and path.exists(self.upload_dir):
                shutil.rmtree(self.upload_dir)
                
    def __unicode__(self):
        return 'Upload [%s] gs%s - %s, %s' % (self.pk, self.import_id, self.name, self.user)


class UploadFile(models.Model):
    upload = models.ForeignKey(Upload, null=True, blank=True)
    file = models.FileField(upload_to="uploads")
    slug = models.SlugField(max_length=50, blank=True)

    def __unicode__(self):
        return self.slug

    @models.permalink
    def get_absolute_url(self):
        return ('data_upload_new', )

    def save(self, *args, **kwargs):
        self.slug = self.file.name
        super(UploadFile, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.file.delete(False)
        super(UploadFile, self).delete(*args, **kwargs)

geonode/catalogue/views.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

import os
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from pycsw import server
from geonode.catalogue.backends.pycsw_local import CONFIGURATION


@csrf_exempt
def csw_global_dispatch(request):
    """pycsw wrapper"""

    # this view should only operate if pycsw_local is the backend
    # else, redirect to the URL of the non-pycsw_local backend
    if (settings.CATALOGUE['default']['ENGINE'] !=
        'geonode.catalogue.backends.pycsw_local'):
        return HttpResponseRedirect(settings.CATALOGUE['default']['URL'])

    mdict = dict(settings.PYCSW['CONFIGURATION'], **CONFIGURATION)

    env = request.META.copy()
    env.update({
            'local.app_root': os.path.dirname(__file__),
            'REQUEST_URI': request.build_absolute_uri(),
            })

    csw = server.Csw(mdict, env)

    content = csw.dispatch_wsgi()

    return HttpResponse(content, content_type=csw.contenttype)

geonode/templates/401.html
{% extends "site_base.html" %}
{% load i18n %}

{% block body %}
    <div id="description"> 
      <h3> 
        {% if error_title %}
          {{ error_title }}
        {% else %}
          {% trans "Not Permitted" %}
        {% endif %}
      </h3>
    </div>
    <p>
    {% if error_message %}
      {{ error_message }}
    {% else %}
      {% blocktrans %}
          You are not allowed to perform this operation.  
      {% endblocktrans %}
    {% endif %}
    </p>
    <p>
    {% if not request.user.is_anonymous %}
    {% blocktrans %}Please verify that you are logged in as the correct user.{%endblocktrans%}
    {% else %}
    {% blocktrans %}Please login or register and retry.{% endblocktrans %}
    {% endif %}
    </p>
{% endblock %}

geonode/templates/_actions.html
{% load i18n %}
<div class="map-actions">
  <a href="#" data-toggle="collapse" data-target="#info"><i class="icon-info-sign"></i> {% trans 'Info' %}</a>
  <a href="#"><i class="icon-heart"></i> {% trans 'Add to Favorites' %}</a>
  <a href="#"><i class="icon-share"></i> {% trans 'Share' %}</a>
  <a href="#" data-toggle="collapse" data-target="#rate-map"><i class="icon-star"></i> {% trans 'Rate this Map' %}</a>
</div>

geonode/templates/_comments.html
{% load dialogos_tags %}
{% load bootstrap_tags %}
{% load pagination_tags %}
{% load url from future %}
{% load friendly_loader %}
{% load i18n %}
{% friendly_load avatar_tags %}

{% load i18n %}
<div id="comments_section" class="comments paginate paginate-manual">
  <header>
    <h3>{% trans 'Comments' %} <span class="total">({% comment_count obj %} total)</span></h3>
  </header>

  {% if user.is_authenticated %}
  <div class="clearfix">
    <a href="#form_post_comment_div" role="button" class="btn pull-right" data-toggle="modal">{% trans 'Add Comment' %}</a>
  </div>
  {% else %}
  <div class="clearfix">
    <p class="pull-right">{% trans 'Log in to add a comment' %}</p>
  </div>
  {% endif %}
  <div class="paginate-contents">
  {% comments obj as comment_list %}
  {% autopaginate comment_list 5 %}
  {% for comment in comment_list %}      
    <article>
      <div class="avatar span1"><a href="{{ comment.author.get_profile.get_absolute_url }}">{% avatar comment.author 40 %}</a></div>
      <div class="pull-left span7">
        <p>{{ comment.comment }}</p>
        <footer>
          <div class="author clearfix span7">
            <p>{% trans 'By' %} <a href="{{ comment.author.get_profile.get_absolute_url }}" rel="author">{{ comment.author }}</a> on <time>{{ comment.submit_date|date:"M j, Y" }}</time></p>
          </div>
        </footer>
      </div>
    </article>
  {% endfor %}
  </div>
  {% paginate %}
</div>

<!-- Modal -->
{% if user.is_authenticated %}
<div id="form_post_comment_div" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>{% trans 'Add a Comment' %}</h3>
    </div>
    <div class="modal-body">
        {% comment_form obj as form %}
        <form action="{% comment_target obj %}" method="POST" id="form_post_comment">
        {% csrf_token %}
        {{ form }}
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">{% trans "Cancel" %}</button>
        <button id="comment_submit_btn" class="btn btn-primary">{% trans 'Submit Comments' %}</button>
    </div>
        </form>
</div>
{% endif %}

geonode/templates/_permissions.html
{% load i18n %}
<div class="modal-body" id="permissions-body" >
  <div class="control-group" id="permission-view-download" >
    <label class="control-label"><strong>{% trans "Who can view and download this data?" %}</strong></label>
    <div class="controls">
      <label class="radio inline">
        <input type="radio" name="viewmode" id="perms_view_anyone" value="ANYONE" checked="checked">
        {% trans "Anyone" %}
      </label>
      <label class="radio inline">
        <input type="radio" name="viewmode" id="perms_view_registered" value="REGISTERED">
        {% trans "Any registered user" %}
      </label>
      <label class="radio inline">
        <input type="radio" name="viewmode" id="perms_view_editors" value="EDITORS">
        {% trans "Only users who can edit" %}
      </label>
    </div>
  </div>
  <div class="control-group" id="permission-edit" >
    <label class="control-label"><strong>{% trans "Who can edit this data?" %}</strong></label>
    <div class="controls">
      <label class="radio">
        <input type="radio" name="editmode" id="perms_edit_registered" value="REGISTERED" checked="checked">
        {% trans "Any registered user" %}
      </label>
      <label class="radio">
        <input type="radio" name="editmode" id="perms_edit_list" value="LIST">
        {% trans "Only the following users:" %}
      </label>
      <input type="text" name="editusers" class="user-select" id="perms_edit_editusers">
      </input>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label"><strong>{% trans "Who can manage and edit this data?" %}</strong></label>
    <div class="controls">
      <input type="text" name="manageusers" class="user-select" id="perms_edit_manageusers">
      </input>
    </div>
  </div>
</div>

geonode/templates/_permissions_form.html
{% load i18n %}

<div class="modal fade" id="modal_perms" style="display:none">
  <form id="permission_form" accept-charset="UTF-8" method="post" class="modal-form" action="{% if layer %}{% url "layer_permissions" layer.typename %}{% elif map %}{% url "map_permissions" map.id %}{% elif document %}{% url "document_permissions" document.id %}{% else %}/api/batch_permissions{% endif %}">
    <div class="modal-header">
      <a class="close" data-dismiss="modal">×</a>
      <h3>{% trans "Permissions" %}</h3>
    </div>
    {% include "_permissions.html" %}
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">{% trans "Cancel" %}</a>
      <a href="#" class="btn btn-primary" data-dismiss="modal" id="perms_submit">{% trans "Apply Changes" %}</a>
    </div>
  </form>
</div>

geonode/templates/_search_js.html
<script>
    $(document).ready(function() {

        $("form.geonode-search").submit(function(e) {
            e.preventDefault();
            var url = $(this).data("search-api");
            var table = $(this).data("results-table");
            var query = $(this).find("input[name=q]").val();

            // Empty results
            $(table).find("tbody").empty();

            // Get results from API
            $.getJSON(url, { q: query }, function(json) {
                if (json["total"] < 1) {
                    $(table).find("tbody:last").append($("#searchNoResultsTemplate").html());
                } else {
                    // Compile template used to render search rows
                    var _results = Hogan.compile($("#searchResultsTemplate").html(), {delimiters: "<% %>"});
                    var results = _results.render(json);
                    $(table).find("tbody:last").append(results).find("abbr.timeago").timeago();
                }
             });
        });

        // Grab url params for initial search
        var urlParams = {};
        (function () {
            var e,
                a = /\+/g,  // Regex for replacing addition symbol with a space
                r = /([^&=]+)=?([^&]*)/g,
                d = function (s) { return decodeURIComponent(s.replace(a, " ")); },
                q = window.location.search.substring(1);

            while (e = r.exec(q))
               urlParams[d(e[1])] = d(e[2]);
        })();
        if (urlParams["q"]) {
          $("input[name=q]").val(urlParams["q"]);
        };
        $("form.geonode-search").submit();
    });
</script>

geonode/templates/about.html
{% extends "site_base.html" %}

{% load i18n %}
{% block title %} {% trans "About GeoNode" %} — {{ block.super }} {% endblock %}

{% block body %}
  <header class="jumbotron subhead" id="overview">
    <h1>{% trans "About GeoNode" %}</h1>
    <p class="lead">{% trans "About GeoNode." %}</p>
  </header>

  <p>Stub</p>

{% endblock %}

geonode/templates/index.html
{% extends "site_base.html" %}
{% load i18n %}
{% load maps_tags %}
{% load layers_tags %}
{% load pagination_tags %}
{% load staticfiles %}
{% load url from future %}

{% block title %} {% trans "Welcome!" %} - {{ block.super }} {% endblock %}

{% block body_class %}home{% endblock %}

{% block body_outer %}
<div class="span12">
  {% block hero %}
  <div class="hero-unit">
    <h1>{% trans "Welcome" %}</h1>
    <div class="hero-unit-content">
      <div class="intro">
        <p>
          {% blocktrans %}
            GeoNode is an open source platform for sharing geospatial data and maps.  If you have any questions about the software or service, join our <a href="https://groups.google.com/d/forum/geonode-users">mailing list</a>.
          {% endblocktrans %}
        </p>
        <span>{% trans 'Need help' %} <a href="http://docs.geonode.org/en/latest/tutorials/users/quickstart/index.html">{% trans 'Getting Started?' %}</a></span>
      </div>
      <div class="btns">
        <a class="btn btn-large" href="{% url "layer_browse" %}">
          {% trans "Explore Layers" %}
        </a>
        <a class="btn btn-large" href="{% url "maps_browse" %}">
          {% trans "Explore Maps" %}
        </a>
      </div>
    </div>
  </div>
  {% endblock %}
  {% block mainbody %}
  <div class="row">
    <div class="span8">
      <section class="widget list paginate-contents">
        <h2>{% trans "Latest Layers" %}</h2>
        <div class="paginate paginate-auto" id="search-content">
          {% include 'search/search_content.html' %}
        </div>
      </section>
    </div>
    <aside class="span4">
      {% if request.user.is_authenticated %}
        <div class="well">
          <section>
            <h2>{% trans "Contribute" %}</h2>
            <p class="main-actions">
            {% blocktrans %}
              GeoNode enables you to upload, manage, and browse data layers. Search for data that is valuable to you, or upload your own data. 
            {% endblocktrans %}
              <a href="{% url "data_upload" %}" class="btn btn-large">{% trans 'Upload Layers' %}</a>
            {% blocktrans %}
              GeoNode enables you to compose and share maps. Create a map with our cartography tool, or explore maps shared by others. 
            {% endblocktrans %}
              <a href="{% url "new_map" %}" class="btn btn-large">{% trans 'Create a Map' %}</a>
            </p>
          </section>
        </div>
      {% endif %}
      <div class="well">
        <h2>{% trans "Latest Maps" %}</h2>
        <section class="article-list latest-maps">
          {% featured_maps as featured_maps %}
          {% for map in featured_maps %}
            {% include "maps/_map_list_item.html" %}
          {% endfor %}
        </section>
      </div>
    </aside>
  </div>
  {% endblock %}
</div>
{% endblock %}

{% block extra_script %}  
  {% include 'search_scripts.html' %}
{% endblock extra_script %}

geonode/templates/metadata_form_js.html
{% load staticfiles %}
{% if DEBUG_STATIC %}
<script src="{% static "lib/js/bootstrap-datepicker.js" %}" type="text/javascript"></script>
{% endif %}
<script type="text/javascript">
{% autoescape off %}
    $(function() {
      $(".datepicker").datepicker();
    });
    
    $('.modal-forms').css('max-height', '500px').css('overflow-y', 'scroll');    
    $('.modal-cloose-btn').css('margin','20px');

    $('.modal-cloose-btn').click(function(){
      $('.modal-forms').modal('hide');
    });

    $('#id_layer-poc').change(function(){
      if($(this).val() === ''){
        $('#poc_form').modal();
      }
    });

    $('#id_layer-metadata_author').change(function(){
      if($(this).val() === ''){
        $('#metadata_form').modal();
      }
    });
{% endautoescape %}
</script> 

geonode/templates/site_base.html
{% extends "base.html" %}