geonode/maps/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls.defaults import patterns, url

js_info_dict = {
    'packages': ('geonode.maps',),
}

urlpatterns = patterns('geonode.maps.views',
    url(r'^$', 'map_list', name='maps_browse'),
    url(r'^tag/(?P<slug>[-\w]+?)/$', 'maps_tag', name='maps_browse_tag'),
    url(r'^new$', 'new_map', name="new_map"),
    url(r'^new/data$', 'new_map_json', name='new_map_json'),
    url(r'^(?P<mapid>\d+)$', 'map_detail', name='map_detail'),
    url(r'^(?P<mapid>\d+)/view$', 'map_view', name='map_view'),
    url(r'^(?P<mapid>\d+)/data$', 'map_json', name='map_json'),
    url(r'^(?P<mapid>\d+)/download$', 'map_download', name='map_download'),
    url(r'^(?P<mapid>\d+)/wmc$', 'map_wmc', name='map_wmc'),
    url(r'^(?P<mapid>\d+)/wms$', 'map_wms', name='map_wms'),
    url(r'^(?P<mapid>\d+)/remove$', 'map_remove', name='map_remove'),
    url(r'^(?P<mapid>\d+)/metadata$', 'map_metadata', name='map_metadata'),
    url(r'^(?P<mapid>\d+)/embed$', 'map_embed', name='map_embed'),
    url(r'^(?P<mapid>\d+)/permissions$', 'map_permissions', name='map_permissions'),
    url(r'^(?P<mapid>\d+)/thumbnail$', 'map_thumbnail', name='map_thumbnail'),
    url(r'^check/$', 'map_download_check', name='map_download_check'),
    url(r'^embed/$', 'map_embed', name='map_embed'),
    url(r'^(?P<layername>[^/]*)/attributes', 'maplayer_attributes', name='maplayer_attributes'),
    #url(r'^change-poc/(?P<ids>\w+)$', 'change_poc', name='maps_change_poc'),
)

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView

import geonode.proxy.urls

# Setup Django Admin
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

    # Static pages
    url(r'^$', 'geonode.views.index', name='home'),
    url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
    url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

    # Layer views
    (r'^layers/', include('geonode.layers.urls')),

    # Map views
    (r'^maps/', include('geonode.maps.urls')),

    # Catalogue views
    (r'^catalogue/', include('geonode.catalogue.urls')),

    # Search views
    (r'^search/', include('geonode.search.urls')),

    # Upload views
    (r'^upload/', include('geonode.upload.urls')),

    # GeoServer Helper Views 
    (r'^gs/', include('geonode.geoserver.urls')),

    # Social views
    (r"^account/", include("account.urls")),
    (r'^people/', include('geonode.people.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^comments/', include('dialogos.urls')),
    (r'^ratings/', include('agon_ratings.urls')),
    (r'^activity/', include('actstream.urls')),
    (r'^announcements/', include('announcements.urls')),
    #(r'^notifications/', include('notification.urls')),
    (r'^messages/', include('user_messages.urls')),
    (r'^social/', include('geonode.social.urls')),
    # Accounts
    url(r'^account/ajax_login$', 'geonode.views.ajax_login',
                                       name='account_ajax_login'),
    url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup',
                                       name='account_ajax_lookup'),

    # Meta
    url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'), name='lang'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
                                  js_info_dict, name='jscat'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                                  {'sitemaps': sitemaps}, name='sitemap'),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^admin/', include(admin.site.urls)),

    )

#Documents views
if settings.DOCUMENTS_APP:
    urlpatterns += patterns('',
        (r'^documents/', include('geonode.documents.urls')),
    )

urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

geonode/layers/models.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
from urlparse import urlparse

import httplib2
import urllib
import logging

from datetime import datetime
from lxml import etree

from django.conf import settings
from django.db import models
from django.db.models import signals
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext, ugettext_lazy as _
from django.core.urlresolvers import reverse

from geonode import GeoNodeException
from geonode.base.models import ResourceBase, ResourceBaseManager, Link, \
    resourcebase_post_save, resourcebase_post_delete
from geonode.utils import  _user, _password, get_wms
from geonode.utils import http_client
from geonode.geoserver.helpers import cascading_delete
from geonode.people.models import Profile
from geonode.security.enumerations import AUTHENTICATED_USERS, ANONYMOUS_USERS
from geonode.layers.ows import wcs_links, wfs_links, wms_links, \
    wps_execute_layer_attribute_statistics
from geonode.layers.enumerations import LAYER_ATTRIBUTE_NUMERIC_DATA_TYPES
from geonode.utils import ogc_server_settings

from geoserver.catalog import Catalog, FailedRequestError
from agon_ratings.models import OverallRating

logger = logging.getLogger("geonode.layers.models")

class Style(models.Model):
    """Model for storing styles.
    """
    name = models.CharField(_('style name'), max_length=255, unique=True)
    sld_title = models.CharField(max_length=255, null=True, blank=True)
    sld_body = models.TextField(_('sld text'), null=True, blank=True)
    sld_version = models.CharField(_('sld version'), max_length=12, null=True, blank=True)
    sld_url = models.CharField(_('sld url'), null = True, max_length=1000)
    workspace = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return "%s" % self.name.encode('utf-8')

class LayerManager(ResourceBaseManager):

    def __init__(self):
        models.Manager.__init__(self)
        url = ogc_server_settings.rest
        self.gs_catalog = Catalog(url, _user, _password)

def add_bbox_query(q, bbox):
    '''modify the queryset q to limit to the provided bbox

    bbox - 4 tuple of floats representing x0,x1,y0,y1
    returns the modified query
    '''
    bbox = map(str, bbox) # 2.6 compat - float to decimal conversion
    q = q.filter(bbox_x0__gte=bbox[0])
    q = q.filter(bbox_x1__lte=bbox[1])
    q = q.filter(bbox_y0__gte=bbox[2])
    return q.filter(bbox_y1__lte=bbox[3])


class Layer(ResourceBase):
    """
    Layer (inherits ResourceBase fields)
    """

    # internal fields
    objects = LayerManager()
    workspace = models.CharField(max_length=128)
    store = models.CharField(max_length=128)
    storeType = models.CharField(max_length=128)
    name = models.CharField(max_length=128)
    typename = models.CharField(max_length=128, unique=True)

    popular_count = models.IntegerField(default=0)
    share_count = models.IntegerField(default=0)

    default_style = models.ForeignKey(Style, related_name='layer_default_style', null=True, blank=True)
    styles = models.ManyToManyField(Style, related_name='layer_styles')

    def update_thumbnail(self, save=True):
        try:
            self.save_thumbnail(self._thumbnail_url(width=200, height=150), save)
        except RuntimeError, e:
            logger.warn('Could not create thumbnail for %s' % self, e)

    def _render_thumbnail(self, spec):
        resp, content = http_client.request(spec)
        if 'ServiceException' in content or resp.status < 200 or resp.status > 299:
            msg = 'Unable to obtain thumbnail: %s' % content
            raise RuntimeError(msg)
        return content


    def _thumbnail_url(self, width=20, height=None):
        """ Generate a URL representing thumbnail of the layer """

        params = {
            'layers': self.typename.encode('utf-8'),
            'format': 'image/png8',
            'width': width,
        }
        if height is not None:
            params['height'] = height

        # Avoid using urllib.urlencode here because it breaks the url.
        # commas and slashes in values get encoded and then cause trouble
        # with the WMS parser.
        p = "&".join("%s=%s"%item for item in params.items())

        return ogc_server_settings.LOCATION + "wms/reflect?" + p


    def verify(self):
        """Makes sure the state of the layer is consistent in GeoServer and Catalogue.
        """

        # Check the layer is in the wms get capabilities record
        # FIXME: Implement caching of capabilities record site wide

        _local_wms = get_wms()
        record = _local_wms.contents.get(self.typename)
        if record is None:
            msg = "WMS Record missing for layer [%s]" % self.typename.encode('utf-8')
            raise GeoNodeException(msg)

    @property
    def display_type(self):
        return ({
            "dataStore" : "Vector Data",
            "coverageStore": "Raster Data",
        }).get(self.storeType, "Data")

    @property
    def store_type(self):
        cat = Layer.objects.gs_catalog
        res = cat.get_resource(self.name)
        res.store.fetch()
        return res.store.dom.find('type').text

    @property
    def service_type(self):
        if self.storeType == 'coverageStore':
            return "WCS"
        if self.storeType == 'dataStore':
            return "WFS"

    def get_absolute_url(self):
        return reverse('layer_detail', args=(self.typename,))

    def attribute_config(self):
        #Get custom attribute sort order and labels if any
            cfg = {}
            visible_attributes =  self.attribute_set.visible()
            if (visible_attributes.count() > 0):
                cfg["getFeatureInfo"] = {
                    "fields":  [l.attribute for l in visible_attributes],
                    "propertyNames":   dict([(l.attribute,l.attribute_label) for l in visible_attributes])
                }
            return cfg

    def __str__(self):
        return "%s Layer" % self.typename.encode('utf-8')

    class Meta:
        # custom permissions,
        # change and delete are standard in django
        permissions = (('view_layer', 'Can view'),
                       ('change_layer_permissions', "Can change permissions"), )

    # Permission Level Constants
    # LEVEL_NONE inherited
    LEVEL_READ  = 'layer_readonly'
    LEVEL_WRITE = 'layer_readwrite'
    LEVEL_ADMIN = 'layer_admin'

    def set_default_permissions(self):
        self.set_gen_level(ANONYMOUS_USERS, self.LEVEL_READ)
        self.set_gen_level(AUTHENTICATED_USERS, self.LEVEL_READ)

        # remove specific user permissions
        current_perms =  self.get_all_level_info()
        for username in current_perms['users'].keys():
            user = User.objects.get(username=username)
            self.set_user_level(user, self.LEVEL_NONE)

        # assign owner admin privileges
        if self.owner:
            self.set_user_level(self.owner, self.LEVEL_ADMIN)

    def tiles_url(self):
        return self.link_set.get(name='Tiles').url

    def maps(self):
        from geonode.maps.models import MapLayer
        return  MapLayer.objects.filter(name=self.typename)

    @property
    def class_name(self):
        return self.__class__.__name__

class Layer_Styles(models.Model):
    layer = models.ForeignKey(Layer)
    style = models.ForeignKey(Style)

class AttributeManager(models.Manager):
    """Helper class to access filtered attributes
    """

    def visible(self):
       return self.get_query_set().filter(visible=True).order_by('display_order')


class Attribute(models.Model):
    """
        Auxiliary model for storing layer attributes.

       This helps reduce the need for runtime lookups
       to GeoServer, and lets users customize attribute titles,
       sort order, and visibility.
    """
    layer = models.ForeignKey(Layer, blank=False, null=False, unique=False, related_name='attribute_set')
    attribute = models.CharField(_('attribute name'), help_text=_('name of attribute as stored in shapefile/spatial database'), max_length=255, blank=False, null=True, unique=False)
    description = models.CharField(_('attribute description'), help_text=_('description of attribute to be used in metadata'), max_length=255, blank=True, null=True)
    attribute_label = models.CharField(_('attribute label'), help_text=_('title of attribute as displayed in GeoNode'), max_length=255, blank=False, null=True, unique=False)
    attribute_type = models.CharField(_('attribute type'), help_text=_('the data type of the attribute (integer, string, geometry, etc)'), max_length=50, blank=False, null=False, default='xsd:string', unique=False)
    visible = models.BooleanField(_('visible?'), help_text=_('specifies if the attribute should be displayed in identify results'), default=True)
    display_order = models.IntegerField(_('display order'), help_text=_('specifies the order in which attribute should be displayed in identify results'), default=1)

    # statistical derivations
    count = models.IntegerField(_('count'), help_text=_('count value for this field'), default=1)

geonode/maps/templates/maps/_map_filters.html
{% load i18n %}
{% load url from future %}

<ul class="nav nav-pills filter">
  <li><a href="{% url "maps_browse" %}" {% if map_filter  == "last_modified" %}class="selected"{% endif %}>{% trans "Most recent" %}</a></li>
  <li><a href="{% url "maps_browse_popular" %}"{% if map_filter == "popular_count" %} class="selected"{% endif %}>{% trans "Most popular" %}</a></li>
  <li><a href="{% url "maps_browse_shared" %}"{% if map_filter == "share_count" %} class="selected"{% endif %}>{% trans "Most shared" %}</a></li>
</ul>

geonode/maps/templates/maps/map_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %}{% block title_sub %}{% trans "Explore Maps" %}{% endblock %} - {{ block.super }} {% endblock %}

{% block body_class %}maps{% endblock %}

{% block body_outer %}
  <div class="span12">
    <ul class="nav nav-tabs" id="subnav-tabs">
          <li><a href="{% url "maps_browse" %}" class="explore">{% trans 'Explore Maps' %}</a></li>
    </ul>
  </div>
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock %}

geonode/maps/templates/maps/map_detail.html
{% extends "maps/map_base.html" %}
{% load geonode_auth %}
{% load i18n %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load url from future %}
{% load base_tags %}

{% block title %}{{ map.title }} — {{ block.super }}{% endblock %}

{% block head %}
{% include "maps/map_include.html" %}
{{ block.super }}
{% endblock %}

{% block body_class %}maps{% endblock %}

{% block body_outer %}
  {% overall_rating map "map" as map_rating %}
  <div class="span6">
    <h2 class="page-title">{{ map.title }}</h2>
  </div>
  <div class="span6 action-group pull-right">
    <div class="btn-group pull-right">
      <div class="btn-group">
        <a class="btn btn-large btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
          {% trans "Download Map" %}
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{% url "map_download" map.pk %}">{% trans "Download Data Layers" %} <i class="icon-chevron-right"></i></a></li>
            <li><a href="{% url "map_wmc" map.pk %}" target="_new">{% trans "Download Web Map Context" %} <i class="icon-chevron-right"></i></a></li>
        </ul>
      </div>

      {% has_obj_perm user map "maps.change_map" as can_edit_map %}
      {% if can_edit_map %}
      <div class="btn-group">
        <a class="btn btn-large btn-info dropdown-toggle" data-toggle="dropdown" href="#">
          {% trans "Edit Map" %}
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{% url "map_metadata" map.id %}">{% trans "Edit Map Metadata" %} <i class="icon-chevron-right"></i></a></li>
          {% if PRINTNG_ENABLED %}
          <li><a href="#" id="set_thumbnail">{% trans "Set Map Thumbnail" %} <i class="icon-chevron-right"></i></a></li>
          {% endif %}
          <li><a href="#modal_perms" data-toggle="modal">{% trans "Edit Map Permissions" %} <i class="icon-chevron-right"></i></a></li>
          <li><a href="{% url "map_remove" map.id %}">{% trans "Remove this Map" %} <i class="icon-chevron-right"></i></a></li>
        </ul>
      </div>
      {% endif %}
      <div class="btn-group">
        <a href="{% url "map_view" map.id %}" class="btn btn-large">{% trans "View Map" %}</a>
      </div>
      {% comment %}
      <div class="btn-group">
        <a href="#" class="btn btn-large btn-info strong"><i class="icon-print icon-white"></i> {% trans "Print Map" %}</a>
      </div>
      {% endcomment %}
    </div>
  </div>
  <div class="span12">
	  <div id="embedded_map" class="mrg-btm">
        <div id="the_map" width='100%'></div>
    </div>
  </div>

  <div class="span8">
    <div class="map-actions">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#info" data-toggle="tab"><i class="icon-info-sign"></i>{% trans "Info" %}</a></li>
        <li><a href="#share" data-toggle="tab"><i class="icon-share"></i>{% trans "Share" %}</a></li>
        <li><a href="#rate" data-toggle="tab"><i class="icon-star"></i>{% trans "Ratings" %}</a></li>
        <li><a href="#comments" data-toggle="tab"><i class="icon-comment"></i> {% trans "Comments" %}</a></li>
        <!-- li><a href="#flag" data-toggle="tab"><i class="icon-flag"></i>{% trans "Flag" %}</a></li -->
      </ul>
    </div>
    <div class="tab-content">

      {% include "base/resourcebase_info_panel.html" with resourcebase=map %}

      <article class="tab-pane" id="comments">
    	{% with map as obj %}
      	{% include "_comments.html" %}
    	{% endwith %}
      </article>
      <article class="tab-pane" id="rate">
        <!-- TODO: Move this to a reusable template snippet -->
        {% if request.user.is_authenticated %}
        <h3>{% trans "Rate this Map" %}</h3>
        {% user_rating request.user map "map" as user_map_rating %}
        <div id="user_rating" class="category-map"></div>
        {% endif %}
        <h3>{% trans 'Average Rating' %}</h3>
        {% overall_rating map "map" as map_rating %}
        {% num_ratings map as num_votes %}
        <div class="overall_rating" style="float:left" data-rating="{{ map_rating }}"></div> ({{num_votes}})
        <!-- TODO: Add display of who gave what rating based -->
      </article>
      <article class="tab-pane" id="share">
        <!-- TODO: Move this to a reusable template snippet -->
        <header>
            <h3>{% trans "Share This Map" %}</h3>
        </header>
        <g:plusone size="small" href="http://{{ request.get_host }}{{ request.get_full_path }}"></g:plusone>
        <div class="fb-like" data-href="http://{{ request.get_host }}{{ request.get_full_path }}" data-send="false" data-width="50" data-layout="button_count" data-show-faces="false"></div>
        <!-- TODO: Add more sharing options -->
      </article>
      <!--article class="tab-pane" id="flag">
        <h2>{% trans "Flag" %}</h2>
      </article-->
    </div>
  </div>
  <aside class="span4">
    <div class='well'>
        <h2>{% trans "Map Layers" %}</h2>
        <p>{% trans "This map uses the following layers:" %}</p>
        <ul class="unstyled space">
          {% for layer in map.layer_set.all %}
	    {% ifnotequal layer.group 'background' %}
		{% if layer.local %}
        	    <li><a href="{% url "layer_detail" layer.name %}">{{ layer.layer_title }}</a></li>
		{% else %}
        	    <li>{{ layer.layer_title }}</li>
		{% endif %}
	    {% endifnotequal %}
          {% endfor %}
        </ul>
    </div>
    {% if documents.count > 0 %}
    <div class="well">
        <h2>{% trans "Documents related to this map" %}</h2>
        <p>{% trans "List of documents related to this map:" %}</p>
        <ul class="unstyled space">
          {% for document in documents %} 
            <li><a href="{{ document.get_absolute_url }}">{{ document.title }}</a></li>
          {% endfor %}
        </ul>
    </div>
    {% endif %}
      {% has_obj_perm user map "maps.change_map_permissions" as can_change_permissions %}
      {% if can_change_permissions %}
    <div class='well'>
        <h2>{% trans "Permissions" %}</h2>
        <p>{% trans "Specify which users can view or modify this map" %}</p>
        <a href="#modal_perms" data-toggle="modal" class="btn btn-large">{% trans "Change Permissions of this Map" %}</a>
    </div>
      {% endif %}
    <div class='well'>
        <h2>{% trans "Copy this map" %}</h2>
        <p>{% trans "Duplicate this map and modify it for your own purposes" %}</p>
        <a href="{% url "new_map" %}?copy={{ map.id }}" class="btn btn-large">{% trans "Create a New Map" %}</a>
    </div>

    {% if map.is_public and can_edit_map or map.layer_group %}
    <div class='well layer-group'>
      <h2>{% trans "Map WMS" %}</h2>
      <dl>{% if map.layer_group %}
        <dt>{% trans "WMS layer group for local map layers" %}:</dt>
        <dd><em>{{ map.layer_group.name }}</em> ({% trans "on" %} <a href="{{ ows }}?request=GetCapabilities">{% trans "local OWS" %}</a>)</dd>
      {% endif %}</dl>
      {% if can_edit_map %}
      <p>{% trans "Publish local map layers as WMS layer group" %}</p>
      <a href="{%url "map_wms" map.id %}" class="btn btn-large">{% trans "Publish Map WMS" %}</a>
      {% endif %}
    </div>
    {% endif %}

    <div class="well last">
    <h2>{% trans "About" %}</h2>
    <p>{% trans "Map Owner" %}</p>
      {% with map.owner.profile as profile %}
        {% include "people/_profile_about_item.html" %} 
      {% endwith %}
    </div>
  </aside>
  {% include "_permissions_form.html" %}
{% endblock %}

{% block extra_script %}
{% if SOCIAL_BUTTONS %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% endif %}
{% if request.user.is_authenticated %}
      {% user_rating_js request.user map "map" %}
{% else %}
      {% overall_rating map "map" as the_map_rating %}
{% endif %}
<script type="text/javascript" src="{{ STATIC_URL}}geonode/js/thumbnail/map_thumbnail.js"></script>
<script type="text/javascript">
 $(function() {
   $('.overall_rating').raty({
     half: true,
     readOnly: true,
     start: $('div.overall_rating').data('rating'),
     path: "{{ STATIC_URL }}lib/img/"
     {% if not request.user.is_authenticated %},
     score: {{ the_map_rating }}
     {% endif %}
   });
   $("#rate-map").raty();

  {% verbatim %}
  // Publish layer group
  // TODO: this should really not be inside a script tag...
  var $wmsBtn = $(".layer-group .btn"),
      layerGroupElTpl;

  if ($wmsBtn.length > 0) {

    $wmsBtn.on("click", function(event) {
      event.preventDefault();

      $.ajax({
        type: "PUT",
        url: $wmsBtn.attr("href")
      })

        .done(function(data) {
          layerGroupElTpl = "<dt>WMS layer group for local map layers:</dt> \
            <dd><em>{{layerGroupName}}</em> (on <a href='{{ows}}?request=GetCapabilities'>local OWS</a>)</dd>";
          $.each(data, function(key, value) {
            // client-side template hack
            layerGroupElTpl = layerGroupElTpl.replace("{{"+ key + "}}", value);
          });
        })

        .fail(function(){
          layerGroupElTpl = "<dt>Error:</dt> \
            <dd>Layer group could not be created.</dd>";
        })

        .always(function(){
          $(".layer-group dl").html(layerGroupElTpl);
        });

    });
  };
  {% endverbatim %}


 });
{% if SOCIAL_BUTTONS %}
 (function() {
   var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
   po.src = 'https://apis.google.com/js/plusone.js';
   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
 })();
{% endif %}
  $("#comment_submit_btn").click(function(event) {
    $.ajax({
      type: "POST",
      url: $("#form_post_comment").attr('action'),
      data: $("#form_post_comment").serialize(),
      success: function() {
        $('#form_post_comment_div').modal('hide');
        $('#comments_section').load(window.location.pathname + ' #comments_section', 
        		function(){$(this).children().unwrap()})
      }
    });
    return false;
  });

{% if PRINTNG_ENABLED %}
  $('#set_thumbnail').click(function(){
    return createMapThumbnail();
  });
{% endif %}
 
</script>
{% include "_permissions_form_js.html" %}
{% endblock %}

geonode/maps/templates/maps/map_view.html
{% extends "site_base.html" %}

{% load i18n %}

{% block title %} {% trans "GeoExplorer" %} - {{ block.super }} {% endblock %}

{% block head %}
{{ block.super }}
{% include 'maps/map_geoexplorer.js' %}

{% endblock %}

{% block footer %}{% endblock %}