geonode/upload/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
from django.conf.urls.defaults import *
from geonode.upload.views import UploadFileCreateView, UploadFileDeleteView

urlpatterns = patterns('geonode.upload.views',
    url(r'^new/$', UploadFileCreateView.as_view(), name='data_upload_new'),
    url(r'^progress$', 'data_upload_progress', name='data_upload_progress'),
    url(r'^(?P<step>\w+)?$', 'view', name='data_upload'),
    url(r'^delete/(?P<id>\d+)?$', 'delete', name='data_upload_delete'),
    url(r'^remove/(?P<pk>\d+)$', UploadFileDeleteView.as_view(), name='data_upload_remove'),
)

geonode/urls.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import include, patterns, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from geonode.sitemap import LayerSitemap, MapSitemap
from django.views.generic import TemplateView

import geonode.proxy.urls

# Setup Django Admin
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('geonode',)
}

sitemaps = {
    "layer": LayerSitemap,
    "map": MapSitemap
}

urlpatterns = patterns('',

    # Static pages
    url(r'^$', 'geonode.views.index', name='home'),
    url(r'^help/$', TemplateView.as_view(template_name='help.html'), name='help'),
    url(r'^developer/$', TemplateView.as_view(template_name='developer.html'), name='developer'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

    # Layer views
    (r'^layers/', include('geonode.layers.urls')),

    # Map views
    (r'^maps/', include('geonode.maps.urls')),

    # Catalogue views
    (r'^catalogue/', include('geonode.catalogue.urls')),

    # Search views
    (r'^search/', include('geonode.search.urls')),

    # Upload views
    (r'^upload/', include('geonode.upload.urls')),

    # GeoServer Helper Views 
    (r'^gs/', include('geonode.geoserver.urls')),

    # Social views
    (r"^account/", include("account.urls")),
    (r'^people/', include('geonode.people.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^comments/', include('dialogos.urls')),
    (r'^ratings/', include('agon_ratings.urls')),
    (r'^activity/', include('actstream.urls')),
    (r'^announcements/', include('announcements.urls')),
    #(r'^notifications/', include('notification.urls')),
    (r'^messages/', include('user_messages.urls')),
    (r'^social/', include('geonode.social.urls')),
    # Accounts
    url(r'^account/ajax_login$', 'geonode.views.ajax_login',
                                       name='account_ajax_login'),
    url(r'^account/ajax_lookup$', 'geonode.views.ajax_lookup',
                                       name='account_ajax_lookup'),

    # Meta
    url(r'^lang\.js$', TemplateView.as_view(template_name='lang.js', content_type='text/javascript'), name='lang'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog',
                                  js_info_dict, name='jscat'),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
                                  {'sitemaps': sitemaps}, name='sitemap'),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^admin/', include(admin.site.urls)),

    )

#Documents views
if settings.DOCUMENTS_APP:
    urlpatterns += patterns('',
        (r'^documents/', include('geonode.documents.urls')),
    )

urlpatterns += geonode.proxy.urls.urlpatterns

# Serve static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler403 = 'geonode.views.err403'

geonode/upload/models.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
from geonode.maps.models import Layer

from geonode.geoserver.uploader.uploader import NotFound
from geonode.upload.utils import gs_uploader
from geonode.utils import ogc_server_settings

from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

import cPickle as pickle
from datetime import datetime
import logging
from os import path
import shutil


class UploadManager(models.Manager):
    def __init__(self):
        models.Manager.__init__(self)
        
    def update_from_session(self, upload_session):
        self.get(import_id = upload_session.import_session.id).update_from_session(upload_session)
        
    def create_from_session(self, user, import_session):
        return self.create(
            user = user, 
            import_id = import_session.id, 
            state= import_session.state)
            
    def get_incomplete_uploads(self, user):
        return self.filter(user=user, complete=False).exclude(state=Upload.STATE_INVALID)
    
        
class Upload(models.Model):
    objects = UploadManager()
    
    import_id = models.BigIntegerField(null=True)
    user = models.ForeignKey(User, null=True)
    # hold importer state or internal state (STATE_)
    state = models.CharField(max_length=16)
    date = models.DateTimeField('date', default = datetime.now)
    layer = models.ForeignKey(Layer, null=True)
    upload_dir = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=64, null=True)
    complete = models.BooleanField(default = False)
    # hold our serialized session object
    session = models.TextField(null=True)
    # hold a dict of any intermediate Layer metadata - not used for now
    metadata = models.TextField(null=True)
    
    class Meta:
        ordering = ['-date']
    
    STATE_INVALID = 'INVALID'
    
    def get_session(self):
        if self.session:
            return pickle.loads(str(self.session))
        
    def update_from_session(self, upload_session):
        self.state = upload_session.import_session.state
        self.date = datetime.now()
        if "COMPLETE" == self.state:
            self.complete = True
            self.session = None
        else:
            self.session = pickle.dumps(upload_session)
        if self.upload_dir is None:
            self.upload_dir = path.dirname(upload_session.base_file)
            self.name = upload_session.layer_title or upload_session.name
        self.save()
        
    def get_resume_url(self):
        return reverse('data_upload') + "?id=%s" % self.import_id
    
    def get_delete_url(self):
        return reverse('data_upload_delete', args=[self.import_id])
        
    def get_import_url(self):
        return "%srest/imports/%s" % (ogc_server_settings.LOCATION, self.import_id)
    
    def delete(self, cascade=True):
        models.Model.delete(self)
        if cascade:
            try:
                session = gs_uploader().get_session(self.import_id)
            except NotFound:
                session = None
            if session:
                try:
                    session.delete()
                except:
                    logging.exception('error deleting upload session')
            if self.upload_dir and path.exists(self.upload_dir):
                shutil.rmtree(self.upload_dir)
                
    def __unicode__(self):
        return 'Upload [%s] gs%s - %s, %s' % (self.pk, self.import_id, self.name, self.user)


class UploadFile(models.Model):
    upload = models.ForeignKey(Upload, null=True, blank=True)
    file = models.FileField(upload_to="uploads")
    slug = models.SlugField(max_length=50, blank=True)

    def __unicode__(self):
        return self.slug

    @models.permalink
    def get_absolute_url(self):
        return ('data_upload_new', )

    def save(self, *args, **kwargs):
        self.slug = self.file.name
        super(UploadFile, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.file.delete(False)
        super(UploadFile, self).delete(*args, **kwargs)

geonode/upload/forms.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################
from django import forms
from django.conf import settings
from geonode.layers.forms import JSONField
from geonode.upload.models import UploadFile 
from geonode.utils import ogc_server_settings
import os
import tempfile
import files

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = UploadFile


class LayerUploadForm(forms.Form):
    base_file = forms.FileField()
    dbf_file = forms.FileField(required=False)
    shx_file = forms.FileField(required=False)
    prj_file = forms.FileField(required=False)
    sld_file = forms.FileField(required=False)
    xml_file = forms.FileField(required=False)

    geogit = forms.BooleanField(required=False)
    geogit_store = forms.CharField(required=False)
    time = forms.BooleanField(required=False)

    abstract = forms.CharField(required=False)
    layer_title = forms.CharField(required=False)
    permissions = JSONField()

    spatial_files = ("base_file", "dbf_file", "shx_file", "prj_file", "sld_file", "xml_file")

    def clean(self):
        requires_datastore = () if ogc_server_settings.DATASTORE else ('.csv','.kml')
        types = [ t for t in files.types if t.code not in requires_datastore]
        supported_type = lambda ext: any([t.matches(ext) for t in types])

        cleaned = super(LayerUploadForm, self).clean()
        base_name, base_ext = os.path.splitext(cleaned["base_file"].name)
        if base_ext.lower() == '.zip':
            # for now, no verification, but this could be unified
            pass
        elif not supported_type(base_ext.lower()[1:]):
            supported = " , ".join([t.name for t in types])
            raise forms.ValidationError("%s files are supported. You uploaded a %s file" % (supported, base_ext))
        if base_ext.lower() == ".shp":
            dbf_file = cleaned["dbf_file"]
            shx_file = cleaned["shx_file"]
            if dbf_file is None or shx_file is None:
                raise forms.ValidationError("When uploading Shapefiles, .SHX and .DBF files are also required.")
            dbf_name, __ = os.path.splitext(dbf_file.name)
            shx_name, __ = os.path.splitext(shx_file.name)
            if dbf_name != base_name or shx_name != base_name:
                raise forms.ValidationError("It looks like you're uploading "
                    "components from different Shapefiles. Please "
                    "double-check your file selections.")
            if cleaned["prj_file"] is not None:
                prj_file = cleaned["prj_file"].name
                if os.path.splitext(prj_file)[0] != base_name:
                    raise forms.ValidationError("It looks like you're "
                        "uploading components from different Shapefiles. "
                        "Please double-check your file selections.")
        return cleaned

    def write_files(self):
        tempdir = tempfile.mkdtemp(dir=settings.FILE_UPLOAD_TEMP_DIR)
        for field in self.spatial_files:
            f = self.cleaned_data[field]
            if f is not None:
                path = os.path.join(tempdir, f.name)
                with open(path, 'w') as writable:
                    for c in f.chunks():
                        writable.write(c)
        absolute_base_file = os.path.join(tempdir,
                self.cleaned_data["base_file"].name)
        return tempdir, absolute_base_file


class TimeForm(forms.Form):
    presentation_strategy = forms.CharField(required=False)
    precision_value = forms.IntegerField(required=False)
    precision_step = forms.ChoiceField(required=False, choices=[
        ('years',)*2,
        ('months',)*2,
        ('days',)*2,
        ('hours',)*2,
        ('minutes',)*2,
        ('seconds',)*2
    ])

    def __init__(self, *args, **kwargs):
        # have to remove these from kwargs or Form gets mad
        time_names = kwargs.pop('time_names', None)
        text_names = kwargs.pop('text_names', None)
        year_names = kwargs.pop('year_names', None)
        super(TimeForm, self).__init__(*args, **kwargs)
        self._build_choice('time_attribute', time_names)
        self._build_choice('end_time_attribute', time_names)
        self._build_choice('text_attribute', text_names)
        self._build_choice('end_text_attribute', text_names)
        if text_names:
            self.fields['text_attribute_format'] = forms.CharField(required=False)
            self.fields['end_text_attribute_format'] = forms.CharField(required=False)
        self._build_choice('year_attribute', year_names)
        self._build_choice('end_year_attribute', year_names)

    def _build_choice(self, att, names):
        if names:
            names.sort()
            choices = [('', '<None>')] + [(a, a) for a in names]
            self.fields[att] = forms.ChoiceField(
                choices=choices, required=False)
    # @todo implement clean


class SRSForm(forms.Form):
    srs = forms.CharField(required=True)

geonode/upload/templates/upload/layer_upload.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %} {% trans "Upload Layer"  %} - {{ block.super }}  {% endblock %}

{% block body_class %}data data-list upload{% endblock %}


{% block head %}

{{ block.super }}
{% endblock %}

{% block body %}
  <div class="block">
    <div class="span8">
      <h2 class="page-title">{% trans "Upload Layers" %}</h2>

        {% if incomplete %}
        <section class="widget" id="incomplete-download-list">
          <h2>{% trans "Incomplete Uploads" %}</h2>
          <p>{% trans "You have the following incomplete uploads" %}:</p>
          {% for u in incomplete %}
          <div class="clearfix uip" id="incomplete-{{ u.import_id }}">
            <div class="pull-left">{{ u.name }}, {% trans "last updated on" %} {{ u.date }}</div>
            <div class="upload_actions pull-right">
              <a class="btn btn-mini" href="#" id="resume-{{ u.import_id }}">{% trans "Resume" %}</a>
              <a class="btn btn-mini" href="#" id="delete-{{ u.import_id }}"><i class="icon-trash"></i> {% trans "Delete" %}</a>
            </div>
          </div>
          {% endfor %}
        </section>
        <div id="confirm-delete" class="hide alert alert-warn" style="padding:10px; margin: 10px 0;">
          {% trans "Are you sure you want to delete this upload?" %}
          <div style="margin: 5px 0">
            <a href="#y" class="btn btn-danger">{% trans "Delete" %}</a>
            <a href="#n" class="btn">{% trans "Cancel" %}</a>
          </div>
          <a href="#yy" style="font-weight:normal">{% trans "Delete, and don't ask me again." %}</a>
        </div>
        {% endif %}

        {% block additional_info %}{% endblock %}

        {% if errors %}
        <div id="errors">
          {% for error in errors %}
          <div>{{ error }}</div>
          {% endfor %}
        </div>
        {% endif %}

        <section id="drop-zone">
          <h2><i class="icon-upload-alt"></i><br />{% trans "Drop files here" %}</h2>
        </section>

        <p>{% trans " or select them one by one:" %}</p>

        <form id="file-uploader" method="post" enctype="multipart/form-data">
          <input class="btn" id="file-input" type="file" multiple>
        </form>

        <section class="widget">
          <ul id="global-errors"></ul>
          <h2>{% trans "Files to be uploaded" %}</h2>
          <div id="file-queue"></div>
        </section>

        <section class="charset">
          <p>{% trans "Select the charset or leave default" %}</p>
          <select id="charset">
            {% for charset in charsets %}
            {% if charset.0 == 'UTF-8' %} 
            <option selected='selected' value={{ charset.0 }}>{{ charset.1 }}</option>
            {% else %}
            <option value={{ charset.0 }}>{{ charset.1 }}</option>
            {% endif %}
            {% endfor %}
          </select>
        </section>

        <section>
          <a href="#" id="upload-button" class="btn pull-right">{% trans "Upload files" %}</a>
          <a href="#" id="clear-button" class="pull-right">{% trans "Clear" %}</a>
        </section>
      </div>
    </div>
{% endblock %}


{% block sidebar %}

{% if GS_SECURITY_ENABLED %}
<h3>{% trans "Permissions"  %}</h3>
<div>
  <form id="permission_form">
  {% include "_permissions.html" %}
  </form>
</div>
{% endif %}

{% endblock %}


{% block extra_script %}
<script data-main="{% static 'geonode/js/upload/main' %}" 
  src="{% static 'lib/js/require.js' %}">
</script>

<script type="text/javascript">
{% autoescape off %}

  csrf_token =  "{{ csrf_token }}",
  form_target = "{{ UPLOADER_URL }}",
  geogit_enabled = {{ GEOGIT_ENABLED|lower  }},
  time_enabled = {{ TIME_ENABLED|lower  }},
  userLookup = "{% url "geonode.views.ajax_lookup" %}"

{% endautoescape %}

</script>
{% if GS_SECURITY_ENABLED %}
{% with "none" as layer %}
{% include "_permissions_form_js.html" %}
{% endwith %}
{% endif %}
{% endblock extra_script %}

geonode/upload/templates/upload/layer_upload_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}data{% endblock %}

{% block body_outer %}
    <div class="span12">
      <!--nav class="back"><a href="{% url "layer_browse" %}"><i class="icon-chevron-left"></i> See all Layers</a></nav-->
      <ul class="nav nav-tabs" id="subnav-tabs">
            <li><a href="{% url "layer_browse" %}" class="explore">{% trans "Explore Layers" %}</a></li>
            <!-- switch to us the new upload -->
            <li><a href="{% url "data_upload" %}" class="upload">{% trans "Upload Layers" %}</a></li>
      </ul>
    </div>
    {% block body %}{% endblock body %}
    {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

geonode/upload/templates/upload/layer_upload_crs.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block body_class %}data data-list upload{% endblock %}

{% block title %} {% trans "Upload Layer" %} - {{ block.super }} {% endblock %}

{% block body %}
  <h2> {% trans "Provide CRS for " %} "{{ layer_name }}" </h2>

  <form method="POST" id="crsForm">
    {% csrf_token %}    
    <h3>{% trans "Coordinate Reference System" %}</h3>
    {% if native_crs %}
    <p>
    {% blocktrans %}
        A coordinate reference system for this layer could not be determined.
        Locate or enter the appropriate ESPG code for this layer below.
        One way to do this is do visit:
        <a href="http://prj2epsg.org/search" target="_">prj2epsg</a>
        and enter the following:
    {% endblocktrans %}
    </p>
    <pre>
    {{ native_crs }}
    </pre>
    <div>
        {{ form.srs.errors }}
        <label for="id_srs">EPSG Code (SRS)  :</label>{{ form.srs }}
    </div>
    <input id='next' type="button" value="{% trans "Next" %}"/>
    {% else %}
    <p>
        {% blocktrans %}
        There is a problem recognizing the projection of this data. Please
        reproject this data to a more common projection.
        {% endblocktrans %}
    </p>
    </p>
    {% endif %}
  </form>
<script data-main="{% static '/geonode/js/upload/srs' %}"
  src="{% static 'lib/js/require.js' %}">
</script>
{% endblock %}

geonode/upload/templates/upload/layer_upload_csv.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% load static from staticfiles %}

{% block body_class %}data data-list upload{% endblock %}

{% block title %} {% trans "Upload Layer" %} - {{ block.super }} {% endblock %}

{% block body %}
{% if present_choices %}
<h2>{% trans "Geospatial Data" %}</h2>
<p>{% trans "Please indicate which attributes contain the latitude and longitude coordinates in the CSV data." %}</p>
{% if guessed_lat_or_lng %}
<p>{% blocktrans %}With this data, GeoNode was able to guess which attributes contain the
latitude and longitude coordinates, but please confirm that the correct
attributes are selected below.{% endblocktrans %}</p>
{% endif %}
<form method="POST" id="csvForm">
  {% csrf_token %}
  {% if error %}
  <div class="msg alert alert-error">{{ error }}</div>
  {% endif %}
  <div>
    <label for="lat" style="display: inline-block; width: 75px">{% trans "Latitude" %}</label>
    <select id="lat" name="lat">
      <option value="None">{% trans "Select an attribute" %}</option>
      {% for option in point_candidates %}
      <option value="{{ option }}"
      {% if selected_lat and selected_lat == option %}
      selected="selected"
      {% endif %}
      >{{ option }}</option>
      {% endfor %}
    </select>
  </div>
  <div style="margin: 10px 0">
    <label for="lat" style="display: inline-block; width: 75px">{% trans "Longitude" %}</label>
    <select id="lng" name="lng">
      <option value="None">{% trans "Select an attribute" %}</option>
      {% for option in point_candidates %}
      <option value="{{ option }}"
      {% if selected_lng and selected_lng == option %}
      selected="selected"
      {% endif %}
      >{{ option }}</option>
      {% endfor %}
    </select>
  </div>
  <a href="#" id="upload-csv-submit" class="btn">{% trans "Next" %}</a>
</form>
<div id="csv-status">
    <div id="status">

    </div>
</div>
{% else %}
<p>{% blocktrans %}We did not detect columns that could be used for the latitude and longitude.
Please verify that you have two columns in your csv file that can be used for
the latitude and longitude.{% endblocktrans %}</p>
{% endif %}
{% endblock %}

{% block extra_script %}
<script data-main="{% static 'geonode/js/upload/csv' %}"
  src="{% static 'lib/js/require.js' %}">
</script>
{% endblock %}

geonode/upload/templates/upload/layer_upload_error.html
{% extends "upload/layer_upload_base.html" %}

{% block body_class %}data data-list upload{% endblock %}

{% block body %}
<div class="twocol">
    <p>{{ error_msg|safe }}
</div>
{% endblock %}

geonode/upload/templates/upload/layer_upload_invalid.html
{% extends "upload/layer_upload_base.html" %}
{% load i18n %}
{% block body_class %}data data-list upload{% endblock %}

{% block body %}
<div class="twocol">
    <p>{% trans "Your upload is either complete or you haven't resumed an earlier one." %}</p>
    <p>{% trans "Return to" %} <a href="{% url "data_upload" %}">{% trans "Upload Form" %}</a>.</p>
</div>
{% endblock %}

geonode/upload/templates/upload/no_upload.html
{% extends "upload/base.html" %}
{% load i18n %}

{% block body %}
<div class="twocol">
    <p>{% trans "Your upload is either complete or you haven't resumed an earlier one." %}</p>
    <p>{% blocktrans %}Returning to the upload starting page in <span id="cnt">5</span>seconds {% endblocktrans %}.</p>
    <p>{% blocktrans %} Or just go {% endblocktrans %}<a href="{% url "data_upload" %}">{% blocktrans %}now{% endblocktrans %}</a>.</p>
</div>
<script type="text/javascript">
    var cnt = 5;
    window.setInterval(function() {
        Ext.get('cnt').dom.innerHTML = cnt--;
        if (cnt == 0) {
            window.location = "{% url "data_upload" %}";
        }
    }, 1000);
</script>
{% endblock %}